# NumPy

In [1]:
import numpy as np

In [2]:
#Create simple array from the list 
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [3]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr=np.array([[10,62,35,40],[55,60,75,85]])

In [5]:
arr

array([[10, 62, 35, 40],
       [55, 60, 75, 85]])

In [6]:
#Dimention of the array
arr.ndim

2

In [7]:
#Shape of the array
arr.shape

(2, 4)

In [8]:
type(arr)

numpy.ndarray

In [9]:
#Memory Location of the array
arr.data

# Random Number Generator using NumPy 

In [10]:
from numpy import random

In [23]:
x=random.randint(1000) #1000 is the limit
x

516

In [31]:
#To Generate multiple numbers in array
x=random.randint(100,size=5)
x

array([ 7, 47, 61, 98, 99])

In [33]:
#Generate Random Float 
x=random.rand()
x

0.3659298274498345

In [34]:
#To Generate multiple float numbers in array
x=random.rand(5)
x

array([0.54431789, 0.01589673, 0.8740578 , 0.04304388, 0.89984909])

In [30]:
#To Generate Random Array
x=random.randint(100,size=(6,2))
x

array([[79, 10],
       [25,  1],
       [77, 83],
       [ 4, 47],
       [74, 94],
       [33, 19]])

In [29]:
x.ndim

2

In [35]:
#x=10 random integer 1D array, range 0 to 1000
#y=10 random integer 1D array, range 0 to 500
#Math Operation

In [36]:
x=random.randint(1000,size=10)
x

array([ 37, 800, 914, 391, 983, 353, 293, 464, 424, 384])

In [38]:
y=random.randint(500,size=10)
y

array([  6, 131, 102,  23, 271, 190,  25, 283,  37, 159])

In [39]:
x+y

array([  43,  931, 1016,  414, 1254,  543,  318,  747,  461,  543])

In [40]:
x-y

array([ 31, 669, 812, 368, 712, 163, 268, 181, 387, 225])

In [41]:
x*y

array([   222, 104800,  93228,   8993, 266393,  67070,   7325, 131312,
        15688,  61056])

In [42]:
x/y

array([ 6.16666667,  6.10687023,  8.96078431, 17.        ,  3.62730627,
        1.85789474, 11.72      ,  1.63957597, 11.45945946,  2.41509434])

# Creating Matrix in NumPy

In [44]:
a=np.matrix('1 2;3 4')
a

matrix([[1, 2],
        [3, 4]])

In [45]:
#Array-like input
b=np.matrix([[5,6,7],[9,10,11]])
b

matrix([[ 5,  6,  7],
        [ 9, 10, 11]])

# Measurement of Central Tendancy using NumPy

In [46]:
arr=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
arr.shape

(3, 3)

In [48]:
#Minimum value
np.min(arr)

5

In [49]:
#Maximum Value
np.max(arr)

45

In [50]:
#Mean
np.mean(arr)

25.0

In [51]:
#Median
np.median(arr)

25.0

In [52]:
#Standard Deviation
np.std(arr)

12.909944487358056

In [53]:
#Variance
np.var(arr)

166.66666666666666